### ISSUE TITLE
compatability issues w/ cds 4.6 -> cds core bug?

### ISSUE THREAD

**Issue by vobu** [sapmentors/cds-pg#101]
trying to upgrade to `cds` 4.6, two tests fail - errors originate in core modules, not in `cds-pg`.
pinging @sjvans for a heads-up (please don't make me file an incident via support launchpad 😬 )

```diff
diff --git a/package.json b/package.json
index 42377ff..a041e7c 100644
--- a/package.json
+++ b/package.json

-    "@sap/cds": "~4.4",
+    "@sap/cds": "~4.6",
```

```bash
$> yarn test

 FAIL  __tests__/lib/pg/service.test.js (10.917 s)
  ● [local] OData to Postgres dialect › odata: DELETE -> sql: DELETE › odata: delete single beer -> sql: delete record

    TypeError: console.warn is not a function

      at Function.warn (node_modules/@sap/cds/lib/utils/logging.js:75:57)
      at _log (node_modules/@sap/cds-runtime/lib/cds-services/adapter/odata-v4/OData.js:71:13)
      at Object.error (node_modules/@sap/cds-runtime/lib/cds-services/adapter/odata-v4/OData.js:83:31)
      at LoggerFacade.error (node_modules/@sap/cds-runtime/lib/cds-services/adapter/odata-v4/okra/odata-commons/logging/LoggerFacade.js:110:20)
      at chainEndCallback (node_modules/@sap/cds-runtime/lib/cds-services/adapter/odata-v4/okra/odata-server/invocation/CommandExecutor.js:36:24)
      at node_modules/@sap/cds-runtime/lib/cds-services/adapter/odata-v4/okra/odata-server/invocation/CommandExecutor.js:82:13
          at runMicrotasks (<anonymous>)

  ● [local-with-schema] OData to Postgres dialect › odata: DELETE -> sql: DELETE › odata: delete single beer -> sql: delete record

    TypeError: console.warn is not a function

      at Function.warn (node_modules/@sap/cds/lib/utils/logging.js:75:57)
      at _log (node_modules/@sap/cds-runtime/lib/cds-services/adapter/odata-v4/OData.js:71:13)
      at Object.error (node_modules/@sap/cds-runtime/lib/cds-services/adapter/odata-v4/OData.js:83:31)
      at LoggerFacade.error (node_modules/@sap/cds-runtime/lib/cds-services/adapter/odata-v4/okra/odata-commons/logging/LoggerFacade.js:110:20)
      at chainEndCallback (node_modules/@sap/cds-runtime/lib/cds-services/adapter/odata-v4/okra/odata-server/invocation/CommandExecutor.js:36:24)
      at node_modules/@sap/cds-runtime/lib/cds-services/adapter/odata-v4/okra/odata-server/invocation/CommandExecutor.js:82:13
          at runMicrotasks (<anonymous>)
```

**Comment by vobu** [comment]
closed via #103
