### ISSUE TITLE
Count request is not working

### ISSUE THREAD

**Issue by rbhuva** [sapmentors/cds-pg#223]
Hello Team,

Count request for an entity is throwing error as below.

url :- Entity/$count
err response:- "could not determine data type of parameter $1"

when I debug the code of cds-pg I can see the query is being generated as:- 
SQL:
SELECT count ( $1 ) AS "counted" FROM CoreService_Job ALIAS_1 LIMIT 1000.
param:["1"]

The inline count is working fine, SQL query is being generated for the inline count as:-
SELECT count ( 1 ) AS "counted" FROM CoreService_Job ALIAS_1 

Thanks,
Rajdeep Bhuva

**Comment by pinakipatrapro** [comment]
Same issue Here

`[cds] - error: could not determine data type of parameter $1
    at Parser.parseErrorMessage (C:\Coding\projects\DashboardLibrary\IBI\node_modules\pg-protocol\dist\parser.js:287:98)
    at Parser.handlePacket (C:\Coding\projects\DashboardLibrary\IBI\node_modules\pg-protocol\dist\parser.js:126:29)
    at Parser.parse (C:\Coding\projects\DashboardLibrary\IBI\node_modules\pg-protocol\dist\parser.js:39:38) 
    at Socket.<anonymous> (C:\Coding\projects\DashboardLibrary\IBI\node_modules\pg-protocol\dist\index.js:11:42)
    at Socket.emit (events.js:315:20)
    at addChunk (internal/streams/readable.js:309:12) 
    at readableAddChunk (internal/streams/readable.js:284:9)
    at Socket.Readable.push (internal/streams/readable.js:223:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:188:23)
    at TCP.callbackTrampoline (internal/async_hooks.js:131:14) {
  length: 111,
  severity: 'ERROR',
  code: '42P18',
  detail: undefined,
  hint: undefined,
  position: undefined,
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'postgres.c',
  line: '1474',
  routine: 'exec_parse_message',
  id: '1968155',
  level: 'ERROR',
  timestamp: 1640333678816
}`


any eta will be really helpful

**Comment by vobu** [comment]
hey, given this is an Open Source project, you might just head over to https://github.com/sapmentors/cds-pg/blob/main/docs/CONTRIBUTING.md that explains in great depth how to get a dev setup going that enables you to give fixing this a try yourself!
Merry 🎄 !

**Comment by gregorwolf** [comment]
@rbhuva @pinakipatrapro please check out the latest release. The issue should be fixed now.

**Comment by rbhuva** [comment]
Thank you @gregorwolf.
It is fixed now.
