### ISSUE TITLE
Connection terminated after multiple INSERT / UPDATES 

### ISSUE THREAD

**Issue by T1mey** [sapmentors/cds-pg#234]
Hello,

using a postgres SQL database on cloud foundry. In an action which retrieves data from an external service and tries to persists
 them into db. For some reason the database connection gets lost... For SQLite DB this coding is working fine... 

```
myArray.forEach(async function (atribute) {
                let system = {                    
                    name: atribute.name,
                    description: atribute.description,
                    index: atribute.index,               
                    sscId: atribute.guid
                };

                let dbEntry = await SELECT.one.from(SAPSystems).where({sscId:system.sscId});

                if (!dbEntry || dbEntry.length === 0) {
                    console.log("INSERT!" + JSON.stringify(system));
                    **await INSERT.into(SAPSystems).entries(system);**
                } else {
                    console.log("UPDATE!" + JSON.stringify(dbEntry) + " with " + JSON.stringify(system));
                    **await UPDATE(SAPSystems).with(system).where({sscId:system.sscId});**
                }                                
});
```

After the action finishes the connection gets lost with the following error:

```
2021-11-16T14:00:47.345+0000 [APP/PROC/WEB/0] ERR [ERROR] Connection terminated
2021-11-16T14:00:47.345+0000 [APP/PROC/WEB/0] ERR     at Connection.<anonymous> (/home/vcap/app/node_modules/pg/lib/client.js:132:36)
2021-11-16T14:00:47.345+0000 [APP/PROC/WEB/0] ERR     at Object.onceWrapper (events.js:482:28)
2021-11-16T14:00:47.345+0000 [APP/PROC/WEB/0] ERR     at Connection.emit (events.js:388:22)
2021-11-16T14:00:47.345+0000 [APP/PROC/WEB/0] ERR     at Socket.<anonymous> (/home/vcap/app/node_modules/pg/lib/connection.js:57:12)
2021-11-16T14:00:47.345+0000 [APP/PROC/WEB/0] ERR     at Socket.emit (events.js:388:22)
2021-11-16T14:00:47.345+0000 [APP/PROC/WEB/0] ERR     at TCP.<anonymous> (net.js:673:12)
2021-11-16T14:00:47.345+0000 [APP/PROC/WEB/0] ERR     at TCP.callbackTrampoline (internal/async_hooks.js:134:14)
2021-11-16T14:00:47.356+0000 [APP/PROC/WEB/0] ERR npm ERR! code ELIFECYCLE
2021-11-16T14:00:47.357+0000 [APP/PROC/WEB/0] ERR npm ERR! errno 1
2021-11-16T14:00:47.360+0000 [APP/PROC/WEB/0] ERR npm ERR! onboarding-tool-cap@1.0.0 start: `cds run`
2021-11-16T14:00:47.360+0000 [APP/PROC/WEB/0] ERR npm ERR! Exit status 1
2021-11-16T14:00:47.360+0000 [APP/PROC/WEB/0] ERR npm ERR! 
2021-11-16T14:00:47.360+0000 [APP/PROC/WEB/0] ERR npm ERR! Failed at the onboarding-tool-cap@1.0.0 start script.
2021-11-16T14:00:47.360+0000 [APP/PROC/WEB/0] ERR npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
2021-11-16T14:00:47.368+0000 [APP/PROC/WEB/0] ERR npm ERR! A complete log of this run can be found in:
2021-11-16T14:00:47.368+0000 [APP/PROC/WEB/0] ERR npm ERR!     /home/vcap/app/.npm/_logs/2021-11-16T14_00_47_360Z-debug.log
2021-11-16T14:00:47.379+0000 [APP/PROC/WEB/0] OUT Exit status 1
2021-11-16T14:00:47.382+0000 [CELL/SSHD/0] OUT Exit status 0
```

**Comment by T1mey** [comment]
changed from forEach to a for loop and now it's working...

**Comment by vobu** [comment]
> changed from forEach to a for loop and now it's working...

which (by glancing at the code you provided) also makes sense - `$array.forEach` causes side-effects, as to where `for-of` does not
