### ISSUE TITLE
_isDraftEnabled not found

### ISSUE THREAD

**Issue by T1mey** [sapmentors/cds-pg#235]
Hello.

I have an error from time to time when opening an object (assuming that was before put into draft state) from worklist by clicking on the  lineitem to navigate to the object.

```
2021-11-17T06:17:57.823+0000 [APP/PROC/WEB/0] OUT [cds] - > READ Applications(ID=b151377e-c2ef-4f00-9ca4-4166cd7283fe,IsActiveEntity=false) {
2021-11-17T06:17:57.823+0000 [APP/PROC/WEB/0] OUT   '$select': 'HasActiveEntity,HasDraftEntity,ID,IsActiveEntity,createdAt,createdBy,description, myInfo',
2021-11-17T06:17:57.823+0000 [APP/PROC/WEB/0] OUT   '$expand': 'DraftAdministrativeData($select=DraftIsCreatedByMe,DraftIsProcessedByMe,DraftUUID,InProcessByUser),status($select=ID,name)'
2021-11-17T06:17:57.823+0000 [APP/PROC/WEB/0] OUT }
2021-11-17T06:17:57.844+0000 [APP/PROC/WEB/0] ERR [cds] - TypeError: Cannot read property '_isDraftEnabled' of undefined
2021-11-17T06:17:57.844+0000 [APP/PROC/WEB/0] ERR     at RawToExpanded._parseRaw (/home/vcap/app/node_modules/cds-pg/node_modules/@sap/cds/libx/_runtime/db/expand/rawToExpanded.js:77:49)
2021-11-17T06:17:57.844+0000 [APP/PROC/WEB/0] ERR     at RawToExpanded._parseMainResult (/home/vcap/app/node_modules/cds-pg/node_modules/@sap/cds/libx/_runtime/db/expand/rawToExpanded.js:40:27)
2021-11-17T06:17:57.844+0000 [APP/PROC/WEB/0] ERR     at RawToExpanded.toExpanded (/home/vcap/app/node_modules/cds-pg/node_modules/@sap/cds/libx/_runtime/db/expand/rawToExpanded.js:29:14)
2021-11-17T06:17:57.844+0000 [APP/PROC/WEB/0] ERR     at runMicrotasks (<anonymous>)
2021-11-17T06:17:57.844+0000 [APP/PROC/WEB/0] ERR     at processTicksAndRejections (internal/process/task_queues.js:95:5)
2021-11-17T06:17:57.844+0000 [APP/PROC/WEB/0] ERR     at async PostgresDatabase.module.exports [as _READ] (/home/vcap/app/node_modules/@sap/cds-runtime/lib/db/generic/read.js:26:18)
2021-11-17T06:17:57.844+0000 [APP/PROC/WEB/0] ERR     at async next (/home/vcap/app/node_modules/@sap/cds/lib/serve/Service-dispatch.js:54:17)
2021-11-17T06:17:57.844+0000 [APP/PROC/WEB/0] ERR     at async PostgresDatabase.dispatch (/home/vcap/app/node_modules/@sap/cds/lib/serve/Service-dispatch.js:52:10)
2021-11-17T06:17:57.844+0000 [APP/PROC/WEB/0] ERR     at async ApplicationService._handler (/home/vcap/app/node_modules/@sap/cds-runtime/lib/fiori/generic/read.js:1136:18)
2021-11-17T06:17:57.844+0000 [APP/PROC/WEB/0] ERR     at async next (/home/vcap/app/node_modules/@sap/cds/lib/serve/Service-dispatch.js:54:17) {
2021-11-17T06:17:57.844+0000 [APP/PROC/WEB/0] ERR   id: '1185446',
2021-11-17T06:17:57.844+0000 [APP/PROC/WEB/0] ERR   level: 'ERROR',
2021-11-17T06:17:57.844+0000 [APP/PROC/WEB/0] ERR   timestamp: 1637129877842
2021-11-17T06:17:57.844+0000 [APP/PROC/WEB/0] ERR }
```

**Comment by vobu** [comment]
it looks by the stack-trace that this error occurs in `cds` core → can you please open a ticket (with more details, such as Node- + cds-Version, db used, etc pp) over at https://launchpad.support.sap.com/ (use BC-XS-CDX-NJS - SAP CAP – Node.js runtime) and/or post your issue at https://answers.sap.com/questions/ask.html?primaryTagId=9f13aee1-834c-4105-8e43-ee442775e5ce
