### ISSUE TITLE
@sap.persistence.skip annotation

### ISSUE THREAD

**Issue by shiVestige** [sapmentors/cds-pg#310]
I tried writing cds services for my RDS instance of postgreSQL. When I try running any of the service like get or post, it's saying entity is defined with @sap.persistence.skip can not be .... but it is working fine with SQLite. what will be the issue with the PostgreSQL, this annotation is calling implicitly by itself.

**Comment by gregorwolf** [comment]
Can you describe in more detail what you like to achieve? The @sap.persistence.skip annotation is intended to be used with a HANA DB where you can reuse existing HANA artifacts like access to other schema using synonyms. Do you have an existing DB schema in PostgreSQL? How was that created? cds-pg supports schema evolution using the [cds-dbm](https://github.com/mikezaschka/cds-dbm) package.

**Comment by gregorwolf** [comment]
Why did you specify `@sap.persistence.skip` for the entities? In my [pg-beershop](https://github.com/gregorwolf/pg-beershop) I have the Brewery entity which is fully draft enabled and allows not only read.

**Comment by AngelGBDev** [comment]
TypeError: Cannot read properties of undefined (reading '@cds.persistence.skip')
    at DataLoader.loadFrom (C:\Users\angel\Documents\GitHub\sdagrosuperdepachobackend\node_modules\cds-dbm\dist\DataLoader.js:52:27)
    at async PostgresAdapter.load (C:\Users\angel\Documents\GitHub\sdagrosuperdepachobackend\node_modules\cds-dbm\dist\adapter\BaseAdapter.js:66:9)
    at async PostgresAdapter.deploy (C:\Users\angel\Documents\GitHub\sdagrosuperdepachobackend\node_modules\cds-dbm\dist\adapter\BaseAdapter.js:183:17)
    at async Object.exports.handler (C:\Users\angel\Documents\GitHub\sdagrosuperdepachobackend\node_modules\cds-dbm\dist\cli\deploy.js:38:9)

**Comment by AngelGBDev** [comment]
Hello Gregor,

I have this problem. Could you give me some solve. 

TypeError: Cannot read properties of undefined (reading '@cds.persistence.skip')
    at DataLoader.loadFrom (C:\Users\angel\Documents\GitHub\sdagrosuperdepachobackend\node_modules\cds-dbm\dist\DataLoader.js:52:27)
    at async PostgresAdapter.load (C:\Users\angel\Documents\GitHub\sdagrosuperdepachobackend\node_modules\cds-dbm\dist\adapter\BaseAdapter.js:66:9)
    at async PostgresAdapter.deploy (C:\Users\angel\Documents\GitHub\sdagrosuperdepachobackend\node_modules\cds-dbm\dist\adapter\BaseAdapter.js:183:17)
    at async Object.exports.handler (C:\Users\angel\Documents\GitHub\sdagrosuperdepachobackend\node_modules\cds-dbm\dist\cli\deploy.js:38:9)
