### ISSUE TITLE
Read mediadata from database.

### ISSUE THREAD

**Issue by mhay-at-dvelop** [sapmentors/cds-pg#337]
Hi,

i use cds-pg to have access to data stored in my postgreSQL datbase from my cap application.
I have an entity with a column storing mediadata. Another column holds media-data.

Following snippet shows the Entitiy in my schema.cds file in CAP

```
  entity Media : managed {
    key Id            : String;
    content           : LargeBinary @Core.MediaType : mediaType;
    mediaType         : String @Core.IsMediaType : true;
    filename          : String;
  }
```

Storing by upload from a fiori-app already works. But now i want to download the media as file by cap via api.
So my request is:

```
GET http://localhost:4004/odata/Media('configjson')/content
```

where configjson is the Id. 

Doing this request throws an exception "TypeError: executeStreamCQN is not a function" in Class/Method **PostgresDatabase._read** from which i think it belongs to this module.

Here is the full stack of the exception:

```
[INTERNAL ERROR] TypeError: executeStreamCQN is not a function
    at PostgresDatabase._read (C:\Daten\localdev\cap\sfsf4dvp\node_modules\@sap\cds\libx\_runtime\db\query\read.js:48:12)
    at PostgresDatabase.module.exports [as _READ] (C:\Daten\localdev\cap\sfsf4dvp\node_modules\@sap\cds\libx\_runtime\db\generic\read.js:15:15)
    at next (C:\Daten\localdev\cap\sfsf4dvp\node_modules\@sap\cds\lib\serve\Service-dispatch.js:74:36)
    at PostgresDatabase.handle (C:\Daten\localdev\cap\sfsf4dvp\node_modules\@sap\cds\lib\serve\Service-dispatch.js:78:6)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async ApplicationService.<anonymous> (C:\Daten\localdev\cap\sfsf4dvp\node_modules\@sap\cds\libx\_runtime\common\generic\crud.js:114:16)
    at async next (C:\Daten\localdev\cap\sfsf4dvp\node_modules\@sap\cds\lib\serve\Service-dispatch.js:74:17)
    at async ApplicationService.handle (C:\Daten\localdev\cap\sfsf4dvp\node_modules\@sap\cds\lib\serve\Service-dispatch.js:72:10)
    at async _readStream (C:\Daten\localdev\cap\sfsf4dvp\node_modules\@sap\cds\libx\_runtime\cds-services\adapter\odata-v4\handlers\read.js:304:16)      
    at async C:\Daten\localdev\cap\sfsf4dvp\node_modules\@sap\cds\libx\_runtime\cds-services\adapter\odata-v4\handlers\read.js:462:16
```

kind regards
Matthias

**Comment by gregorwolf** [comment]
Hi @mhay-at-dvelop,

can do please do the following to make a fix simpler:

- Fork the project
- Create a feature branch
- Add your fields to the TypeChecks entity in __tests__/__assets__/cap-proj/db/schema.cds
- As I don't know a way to provide binary data via the CSV files you should create also a REST Client script for upload. For that you can use [admin-images.http](https://github.com/gregorwolf/bookshop-demo/blob/main/tests/admin-images.http
- Maybe you can also start creating a test

**Comment by vobu** [comment]
and just as a heads-up: in the new `cds-pg`, we refrained from using the pg client's pool and instead re-use the one from the new CAP db layer. That should also enable and simplify stream handling in the new `cds-pg`.
