### ISSUE TITLE
502 Bad Gateway: Registered endpoint failed to handle the request.

### ISSUE THREAD

**Issue by phani0906** [sapmentors/cds-pg#345]
Hello All, 

I deployed mtar file successfully, and the deployment created table in postgres for the entity defined successfully. When I click on the following application route, I can view the metata. However I get the following error when try access the entity records. 

url: https://6d54c149trial-dev-demomta-srv.cfapps.us10.hana.ondemand.com/

Error: 502 Bad Gateway: Registered endpoint failed to handle the request.

Can you please help how to fix it?

Regards,
Phani.

**Comment by vobu** [comment]
Hi, with the little info you provided, it's impossible to guesstimate at any root cause. Please have a look at the logs of your application - any BTP-deployed app allows this via `cf logs <appname>`, `cf dmol`  or via the BTP cockpit.
However, this sounds more like a config/infrastructure issue than related to `cds-pg`.

**Comment by phani0906** [comment]
Thank you vobu for your response. 
Sorry for not posting the logs. Please see the log below.Also, can you please suggest appropriate group to post this question? 

Remote access ended for 10.0.72.3:64186
Exit status 1
npm ERR! A complete log of this run can be found in:
npm ERR! /home/vcap/app/.npm/_logs/2022-09-05T13_44_10_006Z-debug.log
npm ERR! demoMTA@1.0.0 start: `cds run`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the demoMTA@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! errno 1
npm ERR! code ELIFECYCLE
6d54c149trial-dev-demomta-srv.cfapps.us10.hana.ondemand.com - [2022-09-05T13:44:09.935845702Z] "GET /public/Projects HTTP/1.1" 502 0 67 "https://6d54c1.....	
[INTERNAL ERROR] TypeError: Cannot read property 'regularRegex' of undefined
at smartId (/home/vcap/app/node_modules/cds-pg/node_modules/@sap/cds-compiler/lib/sql-identifier.js:66:9)
at _smartId (/home/vcap/app/node_modules/cds-pg/node_modules/@sap/cds/libx/_runtime/common/utils/quotingStyles.js:19:23)
at PGReferenceBuilder._parseReference (/home/vcap/app/node_modules/cds-pg/node_modules/@sap/cds/libx/_runtime/db/sql-builder/ReferenceBuilder.js:106:34)
at PGReferenceBuilder.build (/home/vcap/app/node_modules/cds-pg/lib/pg/sql-builder/ReferenceBuilder.js:44:52)
at PGSelectBuilder._buildRefElement (/home/vcap/app/node_modules/cds-pg/node_modules/@sap/cds/libx/_runtime/db/sql-builder/SelectBuilder.js:272:68)
at PGSelectBuilder._buildElement (/home/vcap/app/node_modules/cds-pg/node_modules/@sap/cds/libx/_runtime/db/sql-builder/SelectBuilder.js:246:18)
at /home/vcap/app/node_modules/cds-pg/node_modules/@sap/cds/libx/_runtime/db/sql-builder/SelectBuilder.js:311:56
[cds] - TypeError: Cannot read property 'regularRegex' of undefined
at smartId (/home/vcap/app/node_modules/cds-pg/node_modules/@sap/cds-compiler/lib/sql-identifier.js:66:9)
at _smartId (/home/vcap/app/node_modules/cds-pg/node_modules/@sap/cds/libx/_runtime/common/utils/quotingStyles.js:19:23)
at PGReferenceBuilder.plain [as _quoteElement] (/home/vcap/app/node_modules/cds-pg/node_modules/@sap/cds/libx/_runtime/common/utils/quotingStyles.js:46:12)
at /home/vcap/app/node_modules/cds-pg/node_modules/@sap/cds/libx/_runtime/db/sql-builder/ReferenceBuilder.js:106:49
at Array.map (<anonymous>)
at PGReferenceBuilder._parseReference (/home/vcap/app/node_modules/cds-pg/node_modules/@sap/cds/libx/_runtime/db/sql-builder/ReferenceBuilder.js:106:34)
at PGReferenceBuilder.build (/home/vcap/app/node_modules/cds-pg/lib/pg/sql-builder/ReferenceBuilder.js:44:52)
at PGSelectBuilder._buildRefElement (/home/vcap/app/node_modules/cds-pg/node_modules/@sap/cds/libx/_runtime/db/sql-builder/SelectBuilder.js:272:68)	
at PGSelectBuilder._buildElement (/home/vcap/app/node_modules/cds-pg/node_modules/@sap/cds/libx/_runtime/db/sql-builder/SelectBuilder.js:246:18)
at /home/vcap/app/node_modules/cds-pg/node_modules/@sap/cds/libx/_runtime/db/sql-builder/SelectBuilder.js:311:56 {id: '1144106',level: 'ERROR',timestamp: 1662385449987}
[cds] - GET /public/Projects
Successful remote access by 10.0.72.3:64186

**Comment by phani0906** [comment]
Sorry, I am new to this platform. Can you please explain how to downgrade to cds^5 ?
