### ISSUE TITLE
Migrate HanaDb To PostgresSQL: Error Casts

### ISSUE THREAD

**Issue by luizcarlospedrosogomes** [sapmentors/cds-pg#356]
cmd: npx cds-dbm build
cmd: npx cds-dbm deploy

error:
`[cds-dbm] - starting delta database deployment of service db
cds-dbm deploy [services]

Dynamically identifies changes in your cds data model and deploys them to the
database

Options:
      --help           Show help                                       [boolean]
      --version        Show version number                             [boolean]
  -s, --service                                                [default: ["db"]]
  -a, --auto-undeploy
  -d, --dry
  -l, --load-via
  -c, --create-db

error: function to_integer(character varying) does not exist
    at Parser.parseErrorMessage (/workspaces/SALESFORCE_API_V2/node_modules/pg-protocol/dist/parser.js:287:98)
    at Parser.handlePacket (/workspaces/SALESFORCE_API_V2/node_modules/pg-protocol/dist/parser.js:126:29)
    at Parser.parse (/workspaces/SALESFORCE_API_V2/node_modules/pg-protocol/dist/parser.js:39:38)
    at Socket.<anonymous> (/workspaces/SALESFORCE_API_V2/node_modules/pg-protocol/dist/index.js:11:42)
    at Socket.emit (events.js:400:28)
    at addChunk (internal/streams/readable.js:293:12)
    at readableAddChunk (internal/streams/readable.js:267:9)
    at Socket.Readable.push (internal/streams/readable.js:206:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:188:23) {
  length: 223,
  severity: 'ERROR',
  code: '42883',
  detail: undefined,
  hint: 'No function matches the given name and argument types. You might need to add explicit type casts.',
  position: '128',
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'parse_func.c',
  line: '629',
  routine: 'ParseFuncOrColumn'
}`

package.json
`{
    "name": "api_cap",
    "version": "1.0.0",
    "description": "A simple CAP project.",
    "repository": "<Add your repository here>",
    "license": "UNLICENSED",
    "private": true,
    "dependencies": {
        "@dynatrace/oneagent-sdk": "^1.4.1",
        "@sap/cds": "^5.9.1",
        "cds-pg": "^0.1.30",
        "cds-dbm": "^0.0.36",
        "@sap/cds-compiler": "^2.1.6",
        "@sap/cds-odata-v2-adapter-proxy": "^1.5.10",
        "@sap/hana-client": "^2.14.22",
        "@sap/hdbext": "^7.7.0",
        "@sap/xsenv": "^3.4.0",
        "@sap/xssec": "^3.2.14",
        "axios": "^0.21.1",
        "axios-cookiejar-support": "^0.5.0",
        "body-parser": "^1.19.0",
        "cors": "^2.8.5",
        "deasync": "^0.1.15",
        "express": "^4.17.1",
        "helmet": "^3.21.2",
        "http-auth": "^4.2.0",
        "jwt-decode": "^3.1.2",
        "mathjs": "^9.4.0",
        "passport": "^0.4.1",
        "request": "^2.88.2",
        "require-dir": "^1.2.0",
        "yargs": "^14.2.0"
    },
    "devDependencies": {
        "sqlite3": "^5.0.2"
    },
    "scripts": {
        "start": "cds run",
        "env": "cp ./default-env.json ./db/default-env.json && cp ./default-env.json ./srv/default-env.json",
        "build": "npm cds build/all --clean",
        "dev": "cds watch"
    },
    "engines": {
        "node": "16.x.x"
    },
    "eslintConfig": {
        "extends": "eslint:recommended",
        "env": {
            "es2020": true,
            "node": true,
            "jest": true,
            "mocha": true
        },
        "globals": {
            "SELECT": true,
            "INSERT": true,
            "UPDATE": true,
            "DELETE": true,
            "CREATE": true,
            "DROP": true,
            "CDL": true,
            "CQL": true,
            "CXL": true,
            "cds": true
        },
        "rules": {
            "no-console": "off",
            "require-atomic-updates": "off"
        }
    },
    "cds": {
        "build": {
            "tasks": [
                {
                    "use": "node-cf",
                    "for": "node-cf",
                    "src": "srv"
                },
                {
                    "use": "postgres-cf",
                    "for": "postgres-cf",
                    "src": "db",
                    "options": {
                        "deployCmd": "npx cds-dbm deploy --load-via delta --auto-undeploy"
                    }
                }
            ]
        },
        "hana": {
            "deploy-format": "hdbtable"
        },
        "requires": {
            "db": {
                "kind": "database"
            },
            "database": {
                "impl": "cds-pg",
                "model": [
                    "srv",
                    "db"
                ]
            },
            "uaa": {
                "kind": "xsuaa"
            },
            "auth": {
                "kind": "basic-auth",
                "users": {
                    "*": true
                }
            }
        },
        "migrations": {
            "db": {
                "schema": {
                    "default": "public",
                    "clone": "_cdsdbm_clone",
                    "reference": "_cdsdbm_ref"
                },
                "deploy": {
                    "tmpFile": "tmp/_autodeploy.json",
                    "undeployFile": "db/undeploy.json"
                }
            }
        }
    }
}
`

**Comment by luizcarlospedrosogomes** [comment]
removed function to_integer from model cds.
