### ISSUE TITLE
PATCH is executed on active entity for drafts with compositions

### ISSUE THREAD

**Issue by willemi069808** [sapmentors/cds-pg#381]
I have a schema like this (simplified):

```
entity Flights {
    key ID         : String(10) @title: 'Flight';
        Prices     : Composition of many Prices
                         on Prices.Flight = $self;
};

entity Prices {
    key UUID                    : UUID;
        Flight                  : Association to one Flights;
        Value                   : Decimal(13, 2) default 0          @title: 'Settlement Value';
        FareBasis               : String(10) default 'xRITS' @title: 'Fare Basis';
        Currency                : Currency                   @title: 'Currency';
};
```

And a service like this (simplified):
```
service MaintainPrices {
    @odata.draft.enabled
    @Common.DraftRoot: {
        NewAction       : 'sap.lts.MaintainPrices.getFlightsDefaults',
        ActivationAction: 'sap.lts.MaintainPrices.draftActivate'
    }
    entity Flights  as projection on my.Flights actions {
        @cds.odata.bindingparameter.collection
        action getFlightsDefaults(FlightID : String @title: 'Flight Number' ) returns Flights;
    };

    entity Prices   as projection on my.Prices;
}
```

For the UI we have standard Fiori Elements, with the Prices displayed as a table on the Object Page of Flights:

```
annotate service.Flights with @(UI: {
...
Facets                           : [
        {
            $Type : 'UI.ReferenceFacet',
            Label : 'Flight Information',
            Target: '@UI.FieldGroup#FlightData'
        },
        {
            $Type : 'UI.ReferenceFacet',
            Label : 'Prices',
            Target: 'Prices/@UI.PresentationVariant'
        }
    ],
...
};
```

The Prices table is configured for inline create/edit in the manifest:
```
"controlConfiguration": {
                                "Prices/@com.sap.vocabularies.UI.v1.LineItem": {
                                    "tableSettings": {
                                        "enableFullScreen": true,
                                        "creationMode": {
                                            "name": "InlineCreationRows"
                                        },
                                        "showCounts": true,
                                        "hideTableTitle": false
                                    }
                                }
                            }
```
So in the application, when clicking on Edit of a Flight, the screen looks like this:

<img width="1680" alt="image" src="https://user-images.githubusercontent.com/19388646/215435523-2b70fe4f-53a8-43b2-acf9-12a9dd837359.png">

## Issue
This works great with cds-pg for read and create, but the edit faces an issue: when changing the Settlement Value of a Price item, a PATCH request is sent to the backend. This PATCH request is different when using "in-memory" vs "postgres" as persistence layer:

When using SQLite / in-memory:
```
[cds] - POST /maintain-prices/$batch 
[cds] - > PATCH Prices(UUID=e0026e7a-413e-4eaf-9485-9c6ce7889005,IsActiveEntity=false)

--batch_id-1675061385385-502
Content-Type:application/http
Content-Transfer-Encoding:binary

PATCH Prices(UUID=e0026e7a-413e-4eaf-9485-9c6ce7889005,IsActiveEntity=false) HTTP/1.1
Accept:application/json;odata.metadata=minimal;IEEE754Compatible=true
Accept-Language:en-US
Prefer:return=minimal
Content-Type:application/json;charset=UTF-8;IEEE754Compatible=true

{"Value":"1899.55"}
--batch_id-1675061385385-502--
Group ID: $auto
```
You can see the PATCH is done on the **IsActiveEntity=false** version.

When using Postgres:
```
[cds] - POST /maintain-prices/$batch 
[cds] - > PATCH Prices(UUID=e0026e7a-413e-4eaf-9485-9c6ce7889005,IsActiveEntity=true) 

--batch_id-1675061249993-933
Content-Type:application/http
Content-Transfer-Encoding:binary

PATCH Prices(UUID=e0026e7a-413e-4eaf-9485-9c6ce7889005,IsActiveEntity=true) HTTP/1.1
Accept:application/json;odata.metadata=minimal;IEEE754Compatible=true
Accept-Language:en-US
Prefer:return=minimal
Content-Type:application/json;charset=UTF-8;IEEE754Compatible=true

{"Value":"1899.56"}
--batch_id-1675061249993-933--
Group ID: $auto



[cds] - Error: Patch can only be applied to a draft entity
    at ODataRequest.reject (/Users/i069808/Software/RITS/lts/cap/node_modules/@sap/cds/lib/req/request.js:67:39)
    at ApplicationService._handler (/Users/i069808/Software/RITS/lts/cap/node_modules/@sap/cds/libx/_runtime/fiori/generic/patch.js:67:47)
    at next (/Users/i069808/Software/RITS/lts/cap/node_modules/@sap/cds/lib/serve/Service-dispatch.js:74:36)
    at ApplicationService.handle (/Users/i069808/Software/RITS/lts/cap/node_modules/@sap/cds/lib/serve/Service-dispatch.js:78:6)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async _updateThenCreate (/Users/i069808/Software/RITS/lts/cap/node_modules/@sap/cds/libx/_runtime/cds-services/adapter/odata-v4/handlers/update.js:97:14)
    at async /Users/i069808/Software/RITS/lts/cap/node_modules/@sap/cds/libx/_runtime/cds-services/adapter/odata-v4/handlers/update.js:156:24 {
  code: 400,
  numericSeverity: 4,
  id: '1327656',
  level: 'ERROR',
  timestamp: 1675060848488
}
```
Here the PATCH is done on the **IsActiveEntity=true**

In the call stack there is no mentioning of the cds-pg module, so I'm not sure why the behavior is different, so feel free to tell me to ask the CAP team..

## Temporary solution
To get around this issue, we are using an override in service.js, but I was hoping there is a cleaner solution:
```
srv.on('PATCH', '*', async (req, next) => {
        if (req.data?.IsActiveEntity == 'true') {
            req.data.IsActiveEntity = 'false';
            console.log('cds-pg bug fix: switched IsActiveEntity to \'false\' for PATCH operation');
        }
        return next();
    });
```

### Versions:
| cap | <Add your repository here> |
|:------------------ | ----------- |
| Node.js            | v16.18.1    |
| @sap/cds           | 5.9.8       |
| @sap/cds-compiler  | 2.15.10     |
| @sap/cds-dk        | 6.3.2       |
| cds-pg | 0.1.33   |
| sqlite3 | 5.1.4 |

**Comment by gregorwolf** [comment]
Hi @willemi069808,

thank you for the detailed issue report. I hope you also aware of [cds-pg → CAP community core](https://github.com/sapmentors/cds-pg/discussions/363). So you maybe can live with your workaround. What you could do anyway would be to improve our test cases and maybe also the Beershop data model so that your issue can be replicated.

Best Regards
Gregor

**Comment by memgavdilabs** [comment]
Hi @gregorwolf,

I have encountered the same issue and have raised this in the sap community https://answers.sap.com/questions/13812048/sap-cap-fiori-elements-v4-object-page-table-edit-f.html

Regards,
Melwyn

**Comment by gregorwolf** [comment]
Ho @memgavdilabs,

have you already tried with the new version that now supports @sap/cds 6.5? If it doesn't work contributions are always welcome but be aware of [cds-pg → CAP community core](https://github.com/sapmentors/cds-pg/discussions/363).

CU
Gregor
