### ISSUE TITLE
Broken draft edit with CDS 4.4

### ISSUE THREAD

**Issue by gregorwolf** [sapmentors/cds-pg#79]
When switching to the edit mode of an existing entity the server crashes with this output:

```
[cds] - POST /beershop-admin/$batch
[cds] - > EDIT TypeChecksWithDraft(ID=5e4ca9ef-7c4c-4b22-8e85-7cadefa02c95,IsActiveEntity=true)/BeershopAdminService.draftEdit {
  '$select': 'HasActiveEntity,HasDraftEntity,ID,IsActiveEntity,type_Boolean,type_Date,type_DateTime,type_Decimal,type_Double,type_Int32,type_Int64,type_LargeString,type_String,type_Time,type_Timestamp',
  '$expand': 'DraftAdministrativeData($select=DraftUUID,InProcessByUser)'
}
[2020-12-09T08:34:27.754Z | ERROR | 1296287]: TypeError: Cannot read property 'includes' of undefined
    at _select (/Users/gwolf/Documents/Projects/cap/pg-beershop/node_modules/@sap/cds-runtime/lib/cds-services/services/handlers/onDraftEdit.js:65:19)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
TypeError: Cannot read property 'includes' of undefined
    at _select (/Users/gwolf/Documents/Projects/cap/pg-beershop/node_modules/@sap/cds-runtime/lib/cds-services/services/handlers/onDraftEdit.js:65:19)
    at processTicksAndRejections (internal/process/task_queues.js:97:5) {
  __crashOnError: true,
  severity: 'Error'
}
```

setting a breakpoint in @sap/cds-runtime/lib/cds-services/services/handlers/onDraftEdit.js:65:19 reveals that the the err object doesn't contain a query element. It seems that we fill the err object with the plain PostgreSQL error:

```
ode:'42601'
column:undefined
constraint:undefined
dataType:undefined
detail:undefined
file:'scan.l'
hint:undefined
internalPosition:undefined
internalQuery:undefined
length:94
line:'1176'
message:'syntax error at or near "WAIT"'
name:'error'
position:'484'
routine:'scanner_yyerror'
schema:undefined
severity:'ERROR'
stack:'error: syntax error at or near "WAIT"
    at Parser.parseErrorMessage (/Users/gwolf/Documents/Projects/cap/pg-beershop/node_modules/pg-protocol/dist/parser.js:278:15)
    at Parser.handlePacket (/Users/gwolf/Documents/Projects/cap/pg-beershop/node_modules/pg-protocol/dist/parser.js:126:29)
    at Parser.parse (/Users/gwolf/Documents/Projects/cap/pg-beershop/node_modules/pg-protocol/dist/parser.js:39:38)
    at Socket.<anonymous> (/Users/gwolf/Documents/Projects/cap/pg-beershop/node_modules/pg-protocol/dist/index.js:10:42)
    at Socket.emit (events.js:311:20)
    at addChunk (_stream_readable.js:294:12)
    at readableAddChunk (_stream_readable.js:275:11)
    at Socket.Readable.push (_stream_readable.js:209:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:186:23)'
table:undefined
where:undefined
```

That's what I can provide for the moment.

**Comment by braunadr** [comment]
Hi Gregor,
I get the same error when trying to click on the "Edit" button on the Object Page. Where you able to find a solution for this? 

Best regrads,
Adrian

**Comment by vobu** [comment]
> I get the same error when trying to click on the "Edit" button on the Object Page. Where you able to find a solution for this?

how about "krempling the ärmel hoch", [setting up the dev env](https://github.com/sapmentors/cds-pg/blob/main/docs/CONTRIBUTING.md#setting-up-the-development-environment), [putting in some breakpoints](https://github.com/sapmentors/cds-pg/blob/main/docs/CONTRIBUTING.md#debugging), and tackling that thing in a PR? 😸

**Comment by gregorwolf** [comment]
Seems the root cause of the issue is the following SQL Statement that is issued when the edit button is clicked:

> [cds-pg] - sql >  SELECT ID AS "ID", type_Boolean AS "type_Boolean", type_Int32 AS "type_Int32", type_Int64 AS "type_Int64", type_Decimal AS "type_Decimal", type_Double AS "type_Double", type_Date AS "type_Date", type_Time AS "type_Time", type_DateTime AS "type_DateTime", type_Timestamp AS "type_Timestamp", type_String AS "type_String", type_Binary AS "type_Binary", type_LargeBinary AS "type_LargeBinary", type_LargeString AS "type_LargeString" FROM csw_TypeChecks ALIAS_1 WHERE ID = $1 FOR UPDATE WAIT 0
> [cds-pg] - values >  [ '5e4ca9ef-7c4c-4b22-8e85-7cadefa02c94' ]

According to the [PostgreSQL SELECT Documentation](https://www.postgresql.org/docs/current/sql-select.html) there is only the `NOWAIT` option but not `WAIT 0`. So we need to adjust the generated SQL.

**Comment by vobu** [comment]
history
