### ISSUE TITLE
Running test for the first time fails on Ubuntu 18.04.5 LTS

### ISSUE THREAD

**Issue by gregorwolf** [sapmentors/cds-pg#8]
I'm starting the test for the first time using:

```
~/Dokumente/Projects/sapcp/cds-pg$ npm test
```

But this test fails with the following errors:

```
> cds-pg@0.0.4 test /home/gwolf/Dokumente/Projects/sapcp/cds-pg
> run-s test:pg:up jest test:pg:down


> cds-pg@0.0.4 test:pg:up /home/gwolf/Dokumente/Projects/sapcp/cds-pg
> docker-compose -f __tests__/__assets__/cap-proj/stack.yml up -d

Creating network "capproj_default" with the default driver
Creating capproj_adminer_1 ... 
Creating capproj_db_1 ... 
Creating capproj_adminer_1
Creating capproj_db_1 ... done

> cds-pg@0.0.4 jest /home/gwolf/Dokumente/Projects/sapcp/cds-pg
> jest

 PASS  __tests__/cqn2pgsql.js
 FAIL  __tests__/odata.js
  ● Console

    console.error
      [2020-08-18T21:46:55.725Z | ERROR | 1957855]: Connection terminated unexpectedly

      at LoggerFacade.error (node_modules/@sap/odata-server/node_modules/@sap/odata-commons/lib/logging/LoggerFacade.js:109:26)
      at chainEndCallback (node_modules/@sap/odata-server/lib/invocation/CommandExecutor.js:37:34)
      at node_modules/@sap/odata-server/lib/invocation/CommandExecutor.js:84:25

    console.error
      [2020-08-18T21:46:55.727Z | ERROR | 1957855]: Error stacktrace: Error: Connection terminated unexpectedly     at Connection.<anonymous> (/home/gwolf/Dokumente/Projects/sapcp/cds-pg/node_modules/pg/lib/client.js:272:71)     at Object.onceWrapper (events.js:421:28)     at Connection.emit (events.js:315:20)     at Socket.<anonymous> (/home/gwolf/Dokumente/Projects/sapcp/cds-pg/node_modules/pg/lib/connection.js:102:10)     at Socket.emit (events.js:327:22)     at endReadableNT (_stream_readable.js:1220:12)     at processTicksAndRejections (internal/process/task_queues.js:84:21)

      at LoggerFacade.error (node_modules/@sap/odata-server/node_modules/@sap/odata-commons/lib/logging/LoggerFacade.js:109:26)
      at chainEndCallback (node_modules/@sap/odata-server/lib/invocation/CommandExecutor.js:38:34)
      at node_modules/@sap/odata-server/lib/invocation/CommandExecutor.js:84:25

    console.log
      {
        error: { code: '500', message: 'Connection terminated unexpectedly' }
      }

      at Object.<anonymous> (__tests__/odata.js:52:17)

    console.error
      [2020-08-18T21:46:55.748Z | ERROR | 1957855]: read ECONNRESET

      at LoggerFacade.error (node_modules/@sap/odata-server/node_modules/@sap/odata-commons/lib/logging/LoggerFacade.js:109:26)
      at chainEndCallback (node_modules/@sap/odata-server/lib/invocation/CommandExecutor.js:37:34)
      at node_modules/@sap/odata-server/lib/invocation/CommandExecutor.js:84:25

    console.error
      [2020-08-18T21:46:55.748Z | ERROR | 1957855]: Error stacktrace: Error: read ECONNRESET     at TCP.onStreamRead (internal/stream_base_commons.js:205:27)

      at LoggerFacade.error (node_modules/@sap/odata-server/node_modules/@sap/odata-commons/lib/logging/LoggerFacade.js:109:26)
      at chainEndCallback (node_modules/@sap/odata-server/lib/invocation/CommandExecutor.js:38:34)
      at node_modules/@sap/odata-server/lib/invocation/CommandExecutor.js:84:25

  ● OData to Postgres dialect › odata: GET -> sql: SELECT › odata: entityset Beers -> sql: select all beers

    expect(received).toStrictEqual(expected) // deep equality

    Expected: 200
    Received: 500

      52 |         console.log(response.body)
      53 |       } 
    > 54 |       expect(response.status).toStrictEqual(200)
         |                               ^
      55 |       // 2 beers in the shop
      56 |       expect(response.body.value.length).toStrictEqual(2)
      57 |       // at least one of them must be the "Lagerbier Hell"

      at Object.<anonymous> (__tests__/odata.js:54:31)

  ● OData to Postgres dialect › odata: GET -> sql: SELECT › odata: entityset Beers -> sql: select all beers

    TypeError: Cannot read property 'release' of undefined

      71 |    */
      72 |   async release() {
    > 73 |     return this.dbc.release(true)
         |                     ^
      74 |   }
      75 | }
      76 | 

      at PostgresDatabase.release (index.js:73:21)
      at Object.<anonymous> (__tests__/odata.js:46:20)

  ● OData to Postgres dialect › odata: GET -> sql: SELECT › odata: single entity -> sql: select record

    expect(received).toStrictEqual(expected) // deep equality

    Expected: 200
    Received: 500

      62 |       const response = await request.get('/beershop/Beers(9e1704e3-6fd0-4a5d-bfb1-13ac47f7976b)')
      63 |       // http response code
    > 64 |       expect(response.status).toStrictEqual(200)
         |                               ^
      65 |       // the beer
      66 |       expect(response.body.ID).toStrictEqual('9e1704e3-6fd0-4a5d-bfb1-13ac47f7976b')
      67 |       expect(response.body.name).toStrictEqual('Schönramer Hell')

      at Object.<anonymous> (__tests__/odata.js:64:31)

  ● OData to Postgres dialect › odata: GET -> sql: SELECT › odata: single entity -> sql: select record

    TypeError: Cannot read property 'release' of undefined

      71 |    */
      72 |   async release() {
    > 73 |     return this.dbc.release(true)
         |                     ^
      74 |   }
      75 | }
      76 | 

      at PostgresDatabase.release (index.js:73:21)
      at Object.<anonymous> (__tests__/odata.js:46:20)

Test Suites: 1 failed, 1 passed, 2 total
Tests:       2 failed, 3 skipped, 7 todo, 2 passed, 14 total
Snapshots:   0 total
Time:        2.146 s
Ran all test suites.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! cds-pg@0.0.4 jest: `jest`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the cds-pg@0.0.4 jest script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/gwolf/.npm/_logs/2020-08-18T21_46_55_888Z-debug.log
ERROR: "jest" exited with 1.
npm ERR! Test failed.  See above for more details.
```

when I run the test the second time it completes without error.  

My node version is 12.18.3, Docker version 19.03.6, build 369ce74a3c, docker-compose version 1.17.1, build unknown

**Comment by vobu** [comment]
given that github actions also run on ubuntu and don't show this behaviour, it smells like a problem in your local env. 
also, the error toward failed socket connections indicate that. 
i'm guessing, you're running postgres on ubuntu in a VM. note that `npm test` boots up its' own docker image with postgres - probably a collision effect btw your postgres in ubuntu and the provided postgres in docker?

**Comment by gregorwolf** [comment]
I've used the Ubuntu Laptop also for developing on https://github.com/gregorwolf/pg-beershop where I've run postgres also in docker. There is no local postgres installation active as it was on my Mac. The strange thing is that it works with the second attempt (when the docker container is already running) but setting a timeout after the docker start doesn't help either.

**Comment by vobu** [comment]
can you peak at the pg logs of the docker image on the laptop once it has started (most likely `/var/log/postgresql`)?
and are there clues in `/var/log/syslog` pertaining to network messages?

**Comment by gregorwolf** [comment]
It seems to be an issue with the /docker-entrypoint-initdb.d/ script. It seems that docker-compose returns control already before the script execution completed. The answer to [How to block until initdb has finished running in a Docker Postgres container?](https://stackoverflow.com/a/48646090/1951652) provides one option.

**Comment by vobu** [comment]
as this is not mission critical (any more), i'm closing the issue
