### ISSUE TITLE
error: could not determine data type of parameter $1 when executing GET /beershop/Beers/$count

### ISSUE THREAD

**Issue by gregorwolf** [sapmentors/cds-pg#89]
Hello cds-pg team,

we have a unit test calling `/beershop/Beers?$count=true`. That works without issues and returns the entities and the element `@odata.count`. But when executing a GET to `/beershop/Beers/$count` the user sees this error message:

```xml
<error xmlns="http://docs.oasis-open.org/odata/ns/metadata">
  <code>42P18</code>
  <message>could not determine data type of parameter $1</message>
</error>
```

when running:

export DEBUG=cds-pg
npm run test:as-pg 

I see this error in the backend:

```
[cds] - GET /beershop/Beers/$count
[cds.cds-pg] - sql >  SELECT count ( $1 ) AS "counted" FROM BeershopService_Beers ALIAS_1
[cds.cds-pg] - values >  [ '1' ]
[2021-02-04T14:31:50.199Z | ERROR | 1847903]: { error: could not determine data type of parameter $1
    at Parser.parseErrorMessage (/Users/gwolf/Documents/Projects/cap/cds-pg/node_modules/pg-protocol/dist/parser.js:278:15)
    at Parser.handlePacket (/Users/gwolf/Documents/Projects/cap/cds-pg/node_modules/pg-protocol/dist/parser.js:126:29)
    at Parser.parse (/Users/gwolf/Documents/Projects/cap/cds-pg/node_modules/pg-protocol/dist/parser.js:39:38)
    at Socket.<anonymous> (/Users/gwolf/Documents/Projects/cap/cds-pg/node_modules/pg-protocol/dist/index.js:10:42)
    at Socket.emit (events.js:311:20)
    at addChunk (_stream_readable.js:294:12)
    at readableAddChunk (_stream_readable.js:275:11)
    at Socket.Readable.push (_stream_readable.js:209:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:186:23)
  length: 111,
  name: 'error',
  severity: 'ERROR',
  code: '42P18',
  detail: undefined,
  hint: undefined,
  position: undefined,
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'postgres.c',
  line: '1496',
  routine: 'exec_parse_message' }
```

I've created a skipped test here: [Branch bug-count Test: /__tests__/lib/pg/service.test.js#L103](https://github.com/gregorwolf/cds-pg/blob/bug-count/__tests__/lib/pg/service.test.js#L103)

CU
Gregor

**Comment by vobu** [comment]
history
