### ISSUE TITLE
Frequently disconnecting

### ISSUE THREAD

**Issue by I304296** [sapmentors/cds-pg#90]
Hi,

I am trying to use cds-pg in my CAP project and the service is frequently crashing with following error:

2021-02-09T23:01:14.07+0000 [APP/PROC/WEB/0] ERR [cds] - GET /public/Votes?$top=11
2021-02-09T23:01:14.17+0000 [RTR/3] OUT 63bc1c00trial-dev-ps-sample-srv.cfapps.us10.hana.ondemand.com - [2021-02-09T23:01:14.065960293Z] "GET /public/Votes?$top=11 HTTP/1.1" 200 0 47 "https://63bc1c00trial-dev-ps-sample-srv.cfapps.us10.hana.ondemand.com/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:85.0) Gecko/20100101 Firefox/85.0" "-" "10.32.2.5:61045" x_forwarded_for:"-" x_forwarded_proto:"https" vcap_request_id:"4f508307-a626-45c0-6d1d-e0108901cde5" response_time:0.109506 gorouter_time:0.000157 app_id:"da9ac238-af17-454f-9b05-b9c9c32102e9" app_index:"0" x_cf_routererror:"-" x_correlationid:"-" tenantid:"-" sap_passport:"-" x_scp_request_id:"eecc0b1f-2611-4463-80f6-b1328dd8353c-60231434-EA5E382" x_cf_app_instance:"-" x_b3_traceid:"73f6b7245a5ffbd2" x_b3_spanid:"73f6b7245a5ffbd2" x_b3_parentspanid:"-" b3:"73f6b7245a5ffbd2-73f6b7245a5ffbd2"
2021-02-09T23:01:14.17+0000 [RTR/3] OUT
2021-02-09T23:01:14.17+0000 [APP/PROC/WEB/0] ERR [ERROR] Release called on client which has already been released to the pool.
2021-02-09T23:01:14.17+0000 [APP/PROC/WEB/0] ERR at throwOnDoubleRelease (/home/vcap/app/node_modules/pg-pool/index.js:27:9)
2021-02-09T23:01:14.17+0000 [APP/PROC/WEB/0] ERR at Client.release (/home/vcap/app/node_modules/pg-pool/index.js:294:9)
2021-02-09T23:01:14.17+0000 [APP/PROC/WEB/0] ERR at PostgresDatabase.release (/home/vcap/app/node_modules/cds-pg/lib/pg/Service.js:177:15)
2021-02-09T23:01:14.17+0000 [APP/PROC/WEB/0] ERR at PostgresDatabase.commit (/home/vcap/app/node_modules/@sap/cds-runtime/lib/db/Service.js:61:10)
2021-02-09T23:01:14.17+0000 [APP/PROC/WEB/0] ERR at process._tickCallback (internal/process/next_tick.js:68:7)
2021-02-09T23:01:14.18+0000 [APP/PROC/WEB/0] ERR npm ERR! code ELIFECYCLE
2021-02-09T23:01:14.18+0000 [APP/PROC/WEB/0] ERR npm ERR! errno 1
2021-02-09T23:01:14.18+0000 [APP/PROC/WEB/0] ERR npm ERR! ps-sample@1.0.0 start: `npx cds run`
2021-02-09T23:01:14.18+0000 [APP/PROC/WEB/0] ERR npm ERR! Exit status 1
2021-02-09T23:01:14.18+0000 [APP/PROC/WEB/0] ERR npm ERR!
2021-02-09T23:01:14.18+0000 [APP/PROC/WEB/0] ERR npm ERR! Failed at the ps-sample@1.0.0 start script.
2021-02-09T23:01:14.18+0000 [APP/PROC/WEB/0] ERR npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
2021-02-09T23:01:14.19+0000 [APP/PROC/WEB/0] ERR npm ERR! A complete log of this run can be found in:
2021-02-09T23:01:14.19+0000 [APP/PROC/WEB/0] ERR npm ERR! /home/vcap/app/.npm/_logs/2021-02-09T23_01_14_190Z-debug.log
2021-02-09T23:01:14.20+0000 [APP/PROC/WEB/0] OUT Exit status 1

**Comment by I304296** [comment]
I guess there is some issue in connection pooling. Is there a way to configure this?

**Comment by vobu** [comment]
too few info as to guess what might cause your postgres connection to be released.
- pg on hyperscaler? docker?
- what version of pg?

aside from that, what's the model and implementation behind `/public/Votes`?

what does the debug log in `/home/vcap/app/.npm/_logs/2021-02-09T23_01_14_190Z-debug.log` tell you?

**Comment by I304296** [comment]
Thanks for reply. 
Sorry missed out some info. Please find below:
1. This is deployed on SCP trial 
2. Used PostgreSQL service on SCP (plan trial)
3. Used Business Apps Studio for development

I following this blog by Mike:
https://blogs.sap.com/2020/11/30/run-and-deploy-cap-with-postgresql-on-sap-cloud-platform-cloud-foundry-node.js/
and used the same code base as in this git repo:
https://github.com/mikezaschka/cap-devtoberfest.git

Data model as below:
using { cuid } from '@sap/cds/common';

namespace db;

entity Projects: cuid {
  name : String(150);
  language: String(150);
  repository: String;
  votes: Association to many Votes on votes.project = $self;
}

entity Votes: cuid {
  username : String(150);
  createdAt: DateTime;
  project: Association to one Projects;
}

And Service is as below:
using db from '../db/data-model';

service PublicService {
    entity Projects as projection on db.Projects;
    entity Votes as projection on db.Votes;
}

Node version: v10.23.1

**Comment by I304296** [comment]
Since I am running it from my Business Apps Studio, I am not sure how to download the log from /home/vcap/app/.npm/_logs/2021-02-09T23_01_14_190Z-debug.log

The log that I posted was found from cf logs <app> --recent

**Comment by vobu** [comment]
> Since I am running it from my Business Apps Studio, I am not sure how to download the log from /home/vcap/app/.npm/_logs/2021-02-09T23_01_14_190Z-debug.log
> 
> 
> 
> The log that I posted was found from cf logs <app> --recent

you can ssh into your app-container and retrieve the log file

**Comment by vobu** [comment]
> Sorry missed out some info. Please find below:
> 
> 1. This is deployed on SCP trial 
> 
> 2. Used PostgreSQL service on SCP (plan trial)
> 
> 3. Used Business Apps Studio for development
> 
> 
> 
> I following this blog by Mike:
> 
> https://blogs.sap.com/2020/11/30/run-and-deploy-cap-with-postgresql-on-sap-cloud-platform-cloud-foundry-node.js/
> 
> and used the same code base as in this git repo:
> 
> https://github.com/mikezaschka/cap-devtoberfest.git
> 
> 
> 
> Data model as below:
> 
> using { cuid } from '@sap/cds/common';
> 
> 
> 
> namespace db;
> 
> 
> 
> entity Projects: cuid {
> 
>   name : String(150);
> 
>   language: String(150);
> 
>   repository: String;
> 
>   votes: Association to many Votes on votes.project = $self;
> 
> }
> 
> 
> 
> entity Votes: cuid {
> 
>   username : String(150);
> 
>   createdAt: DateTime;
> 
>   project: Association to one Projects;
> 
> }
> 
> 
> 
> And Service is as below:
> 
> using db from '../db/data-model';
> 
> 
> 
> service PublicService {
> 
>     entity Projects as projection on db.Projects;
> 
>     entity Votes as projection on db.Votes;
> 
> }
> 
> 
> 
> Node version: v10.23.1

hm, looks perfectly legit, by the books. what version of postgres did you instantiate on sap btp?
quick idea: try using node 12+
any other ideas what might cause the disconnects, @mikezaschka or @gregorwolf?

**Comment by vobu** [comment]
closing this due to no activity
